#!/bin/bash

set -e

#TODO I need to inject user .jwt so command line can upload data.. is there a better way?
jwt=$(jq -r .jwt config.json)
echo -n $jwt > .jwt

set -x

project=$(jq -r .project config.json)
sessionid=$(jq -r .sessionid config.json)

if [ ! -z $BLHOST ]; then
  export SINGULARITYENV_BLHOST=$BLHOST
else
  BLHOST=brainlife.io
fi

singularity exec -e \
  -B $EZBIDS \
  -B `pwd`/.jwt:$HOME/.config/$BLHOST/.jwt docker://brainlife/cli exit 1
#bl bids upload -p $project $EZBIDS/$sessionid/bids

